name: 'custom github action'
description: 'take number and return the square od number'
inputs:
  num:
      requires: true
      default: "1"
outputs:
  num_sqared:
    value: ${{}}
runs:
  using: 'composite'
  steps:
  - name: Setup Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.10'
  - name: install dependencies
    run: pip install -r requirements.txt
    shell: bash
  - name: pass inputs to shell
    run:
      echo "INPUT_NUM=${{inputs.num}}" >> $study
    shell: bash
  - name: fetch s=the number' square
